### ISSUE TITLE
Built-in keyboard for passphrase entry

### ISSUE THREAD

**Issue by smblott-github** [sas101/pass-android#3]
Do you really think this is necessary?  At least in the first instance?

The status quo is that, when entering passwords, I have to trust my keyboard and my app (which may be a browser).  I'd say it's enough to be at least that secure.  Again, at least in the first instance.

**Comment by kevincox** [comment]
I agree.  If you can't trust your keyboard you are screwed already.  I think you are gaining very little and losing a lot by using a custom keyboard.
