### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by Beanow** [sas101/pass-android#7]
The license will determine a lot in terms of freedoms, landscape of the contributors and users that will find use for the application.

For reference:
- `pass`: GPL v2 and later
- `gnupg for android`: GPL v3 and later
- `openpgp-keychain`: GPL v3

While I would recommend GPL either way, using significant code from a GPL project requires you to use GPL as well. Side-by-side installations (for example if you use androids intents instead of adopting the code) do not require this.

**Comment by bhaavanmerchant** [comment]
Would it not be prudent to use GPL v3 only? What are the arguments against using it?

One that I can imagine is:
App creation by 3rd parties, using this as core code, but packaging in their own refined User Interface to add value, and make the app proposition beautiful and viable. If they do add this value, they should be provided some freedom to not necessary open source their code.
